In [12]:
import time

import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler

pd.set_option("display.max_rows", None)  # or a specific number
pd.set_option("display.max_columns", None)  # to show all columns
pd.set_option("display.expand_frame_repr", False)  # to allow wider DataFrame display

In [13]:
features = pd.read_csv("features/features.csv", index_col='match_id')

In [15]:
features.head()

          start_time  lobby_type  r1_hero  r1_level  r1_xp  r1_gold  r1_lh  r1_kills  r1_deaths  r1_items  r2_hero  r2_level  r2_xp  r2_gold  r2_lh  r2_kills  r2_deaths  r2_items  r3_hero  r3_level  r3_xp  r3_gold  r3_lh  r3_kills  r3_deaths  r3_items  r4_hero  r4_level  r4_xp  r4_gold  r4_lh  r4_kills  r4_deaths  r4_items  r5_hero  r5_level  r5_xp  r5_gold  r5_lh  r5_kills  r5_deaths  r5_items  d1_hero  d1_level  d1_xp  d1_gold  d1_lh  d1_kills  d1_deaths  d1_items  d2_hero  d2_level  d2_xp  d2_gold  d2_lh  d2_kills  d2_deaths  d2_items  d3_hero  d3_level  d3_xp  d3_gold  d3_lh  d3_kills  d3_deaths  d3_items  d4_hero  d4_level  d4_xp  d4_gold  d4_lh  d4_kills  d4_deaths  d4_items  d5_hero  d5_level  d5_xp  d5_gold  d5_lh  d5_kills  d5_deaths  d5_items  first_blood_time  first_blood_team  first_blood_player1  first_blood_player2  radiant_bottle_time  radiant_courier_time  radiant_flying_courier_time  radiant_tpscroll_count  radiant_boots_count  radiant_ward_observer_count  radiant_ward_sentry_count  radiant_first_ward_time  dire_bottle_time  dire_courier_time  dire_flying_courier_time  dire_tpscroll_count  dire_boots_count  dire_ward_observer_count  dire_ward_sentry_count  dire_first_ward_time  duration  radiant_win  tower_status_radiant  tower_status_dire  barracks_status_radiant  barracks_status_dire
match_id
0         1430198770           7       11         5   2098     1489     20         0          0         7       67         3    842      991     10         0          0         4       29         5   1909     1143     10         0          0         8       20         3    757      741      6         0          0         7      105         3    732      658      4         0          1        11        4         3   1058      996     12         0          0         6       42         4   1085      986     12         0          0         4       21         5   2052     1536     23         0          0         6       37         3    742      500      2         0          0         8       84         3    958     1003      3         1          0         9               7.0               1.0                  9.0                  NaN                134.0                 -80.0                        244.0                       2                    2                            2                          0                     35.0             103.0              -84.0                     221.0                    3                 4                         2                       2                 -52.0      2874            1                  1796                  0                       51                     0
1         1430220345           0       42         4   1188     1033      9         0          1        12       49         4   1596      993     10         0          1         7       67         4   1506     1502     18         1          0         7       37         3    669      631      7         0          0         7       26         2    415      539      1         0          0         5       39         5   1960     1384     16         0          0         8       88         3    640      566      1         0          1         5       79         3    720     1350      2         2          0        12        7         2    440      583      0         0          0         7       12         4   1470     1622     24         0          0         9              54.0               1.0                  7.0                  NaN                173.0                 -80.0                          NaN                       2                    0                            2                          0                    -20.0             149.0              -84.0                     195.0                    5                 4                         3                       1                  -5.0      2463            1                  1974                  0                       63                     1
2         1430227081           7       33         4   1319     1270     22         0          0        12       98         3   1314      775      6         0          0         6       20         3   1297      909      0         1          0         6       27         5   2360     2096     26         1          1         6        4         3   1395     1627     27         0          0         9       22         5   2305     2028     19         1          1        10       66         3   1024      959     19         0          1        10       86         3    755      620      3         0          0         8       29         4   1319      667      4         0          0         7       80         3   1350     1512     25         0          0         7             224.0               0.0                  3.0                  NaN                 63.0                 -82.0                          NaN                       2                    5                            2                          1                    -39.0              45.0              -77.0                     221.0                    3                 4                         3                       1                  13.0      2130            0                     0               1830                        0                    63
3         1430263531           1       29         4   1779     1056     14         0          0         5       30         2    539      539      1         0          0         6       75         5   2037     1139     15         0          0         6       37         2    591      499      0         0          0         6       41         3    712     1075     12         0          0         6       96         5   1878     1174     17         0          0         6       48         3    732     1468     22         0          0        10       15         4   1681     1051     11         0          0         7      102         2    674      537      1         0          0         7       20         2    510      499      0         0          0         7               NaN               NaN                  NaN                  NaN                208.0                 -75.0                          NaN                       0                    3                            2                          0                    -30.0             124.0              -80.0                     184.0                    0                 4                         2                       0                  27.0      1459            0                  1920               2047                       50                    63
4         1430282290           7       13         4   1431     1090      8         1          0         8       27         2    629      552      0         0          1         7       30         3    884      927      0         1          0         8       72         3    925     1439     16         1          0        11       93         4   1482      880      7         0          0         8       26         3    704      586      1         0          2         9       69         3   1169     1665     20         1          0         7       22         3   1055      638      1         0          0         9       25         5   1815     1275     18         0          0         8        8         4   1119      904      6         0          1         7             -21.0               1.0                  6.0                  NaN                166.0                 -81.0                        181.0                       1                    4                            2                          0                     46.0             182.0              -80.0                     225.0                    6                 3                         3                       0                 -16.0      2449            0                     4               1974                        3                    63

In [16]:
nafeat = features.isna().any()
print(*list(nafeat[nafeat].index), sep=", ")

first_blood_time, first_blood_team, first_blood_player1, first_blood_player2, radiant_bottle_time, radiant_courier_time, radiant_flying_courier_time, radiant_first_ward_time, dire_bottle_time, dire_courier_time, dire_flying_courier_time, dire_first_ward_time

In [17]:
target_col = "radiant_win"
features_to_remove = [
    "duration",
    "tower_status_radiant",
    "tower_status_dire",
    "barracks_status_dire",
    "barracks_status_radiant",
]
y = features[target_col].copy()
X = features.drop(features_to_remove + [target_col], axis=1)
X = X.fillna(0)

In [18]:
kf = KFold(n_splits=5, shuffle=True, random_state=241)

In [19]:
for n_estimators in [10, 20, 30, 50, 100]:
    print(f"n_estimators={n_estimators}")
    for i, (train_ind, test_ind) in enumerate(kf.split(X, y)):
        start = time.time()
        gbc = GradientBoostingClassifier(n_estimators=10, random_state=241)
        gbc.fit(X.iloc[train_ind], y.iloc[train_ind])
        y_pred_proba = gbc.predict_proba(X.iloc[test_ind])[:, 1]
        auc_roc = roc_auc_score(y_true=y.iloc[test_ind], y_score=y_pred_proba)
        print(f"iter={i} | AUC-ROC: {auc_roc} | time: {int(time.time() - start)} sec")
    print("\n")

n_estimators=10
iter=0 | AUC-ROC: 0.669434961810888 | time: 11 sec
iter=1 | AUC-ROC: 0.6562775358072253 | time: 9 sec
iter=2 | AUC-ROC: 0.6639045440221887 | time: 7 sec
iter=3 | AUC-ROC: 0.6628122296043026 | time: 7 sec
iter=4 | AUC-ROC: 0.6695093319282661 | time: 7 sec


n_estimators=20
iter=0 | AUC-ROC: 0.669434961810888 | time: 7 sec
iter=1 | AUC-ROC: 0.6562775358072253 | time: 7 sec
iter=2 | AUC-ROC: 0.6639045440221887 | time: 7 sec
iter=3 | AUC-ROC: 0.6628122296043026 | time: 7 sec
iter=4 | AUC-ROC: 0.6695093319282661 | time: 7 sec


n_estimators=30
iter=0 | AUC-ROC: 0.669434961810888 | time: 7 sec
iter=1 | AUC-ROC: 0.6562775358072253 | time: 7 sec
iter=2 | AUC-ROC: 0.6639045440221887 | time: 7 sec
iter=3 | AUC-ROC: 0.6628122296043026 | time: 7 sec
iter=4 | AUC-ROC: 0.6695093319282661 | time: 7 sec


n_estimators=50
iter=0 | AUC-ROC: 0.669434961810888 | time: 7 sec
iter=1 | AUC-ROC: 0.6562775358072253 | time: 7 sec
iter=2 | AUC-ROC: 0.6639045440221887 | time: 7 sec
iter=3 | AUC-ROC: 0.6628122296043026 | time: 7 sec
iter=4 | AUC-ROC: 0.6695093319282661 | time: 7 sec


n_estimators=100
iter=0 | AUC-ROC: 0.669434961810888 | time: 7 sec
iter=1 | AUC-ROC: 0.6562775358072253 | time: 7 sec
iter=2 | AUC-ROC: 0.6639045440221887 | time: 7 sec
iter=3 | AUC-ROC: 0.6628122296043026 | time: 7 sec
iter=4 | AUC-ROC: 0.6695093319282661 | time: 7 sec

In [ ]:
for i, (train_ind, test_ind) in enumerate(kf.split(X, y)):
    gbc = LogisticRegression(
        random_state=241,
        max_iter=1000,
        penalty="l2",
        C=2.0,
    )
    gbc.fit(X.iloc[train_ind], y.iloc[train_ind])
    y_pred_proba = gbc.predict_proba(X.iloc[test_ind])[:, 1]
    auc_roc = roc_auc_score(y_true=y.iloc[test_ind], y_score=y_pred_proba)
    print(f"iter={i} | AUC-ROC: {auc_roc}")

iter=0 | AUC-ROC: 0.7155881604434065
iter=1 | AUC-ROC: 0.7073065507797573
iter=2 | AUC-ROC: 0.7094219347563149
iter=3 | AUC-ROC: 0.709286767356042
iter=4 | AUC-ROC: 0.7119534057999023

In [12]:
X.describe()

            match_id    start_time    lobby_type       r1_hero      r1_level         r1_xp       r1_gold         r1_lh      r1_kills     r1_deaths      r1_items       r2_hero      r2_level         r2_xp       r2_gold         r2_lh      r2_kills     r2_deaths      r2_items       r3_hero      r3_level         r3_xp       r3_gold         r3_lh      r3_kills     r3_deaths      r3_items       r4_hero      r4_level         r4_xp       r4_gold         r4_lh      r4_kills     r4_deaths      r4_items       r5_hero      r5_level         r5_xp       r5_gold         r5_lh      r5_kills     r5_deaths      r5_items       d1_hero      d1_level         d1_xp       d1_gold         d1_lh      d1_kills     d1_deaths      d1_items       d2_hero      d2_level         d2_xp       d2_gold         d2_lh      d2_kills     d2_deaths      d2_items       d3_hero      d3_level         d3_xp       d3_gold         d3_lh      d3_kills     d3_deaths      d3_items       d4_hero      d4_level         d4_xp       d4_gold         d4_lh      d4_kills     d4_deaths      d4_items       d5_hero      d5_level         d5_xp       d5_gold         d5_lh      d5_kills     d5_deaths      d5_items  first_blood_time  first_blood_team  first_blood_player1  first_blood_player2  radiant_bottle_time  radiant_courier_time  radiant_flying_courier_time  radiant_tpscroll_count  radiant_boots_count  radiant_ward_observer_count  radiant_ward_sentry_count  radiant_first_ward_time  dire_bottle_time  dire_courier_time  dire_flying_courier_time  dire_tpscroll_count  dire_boots_count  dire_ward_observer_count  dire_ward_sentry_count  dire_first_ward_time
count   97230.000000  9.723000e+04  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000  97230.000000      97230.000000      97230.000000         97230.000000         97230.000000         97230.000000          97230.000000                 97230.000000            97230.000000         97230.000000                 97230.000000               97230.000000             97230.000000      97230.000000       97230.000000              97230.000000         97230.000000      97230.000000              97230.000000            97230.000000          97230.000000
mean    57185.416744  1.444232e+09      2.630999     51.517104      3.442672   1233.405801   1147.899702     11.231996      0.357009      0.362285      8.271315     52.183452      3.364661   1189.223676   1107.863993     10.471747      0.348709      0.363550      8.275584     52.710491      3.353924   1182.879965   1099.643742     10.333004      0.342723      0.357338      8.273527     52.648092      3.308896   1159.088481   1082.090240      9.981909      0.337746      0.357307      8.275049     52.625630      3.304237   1158.586167   1082.057061      9.995351      0.337262      0.352782      8.288491     51.990106      3.461123   1238.855765   1151.018184     11.253841      0.372262      0.344091      8.296380     52.708547      3.388933   1199.858809   1108.633436     10.460424      0.356238      0.347012      8.310419     52.755137      3.378638   1193.554438   1103.273702     10.386918      0.353533      0.347732      8.305420     52.922421      3.337725   1171.952155   1088.711653     10.035349      0.354952      0.341860      8.319665     53.059694      3.345274   1177.395351   1089.558850     10.053739      0.356063      0.342538      8.323048         78.042919          0.416878             3.669732             2.400247           106.337200            -79.489715                   154.945161                2.994775             3.312527                     2.431719                   0.716250                -6.745912        106.093644         -79.634352                157.196040             2.965566          3.349553                  2.448339                0.689119             -6.772303
std     33007.123878  5.515393e+06      2.835761     32.564211      1.111741    566.588895    464.111662      9.041620      0.663889      0.626704      2.497575     32.674077      1.097536    555.363510    458.001007      8.972073      0.654060      0.624236      2.433864     32.560923      1.092126    554.899600    454.727127      8.950871      0.647774      0.618071      2.440139     32.670519      1.092502    550.937530    450.353291      8.917997      0.642908      0.616181      2.427832     32.608231      1.095842    553.020429    453.165214      8.948413      0.643538      0.614965      2.430826     32.442153      1.104905    560.550962    459.111207      9.007098      0.678321      0.609487      2.472106     32.500960      1.088991    551.118181    450.268322      8.889886      0.659384      0.608894      2.428835     32.421325      1.088969    550.704105    450.015146      8.901528      0.656819      0.608922      2.434323     32.460902      1.085221    547.308063    448.416794      8.872503      0.658713      0.602357      2.427417     32.535112      1.091848    550.887551    449.877513      8.882013      0.659190      0.605956      2.432850         83.589946          0.493045             3.169938             3.045166            73.078298             17.134835                   101.574206                1.933283             1.154414                     0.811435                   0.725331                39.145035         74.111528          16.604443                 99.593382             1.907288          1.155609                  0.813459                0.710122             40.328277
min         0.000000  1.430199e+09      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000        -78.000000          0.000000             0.000000             0.000000           -37.000000            -90.000000                     0.000000                0.000000             0.000000                     0.000000                   0.000000              -236.000000        -45.000000         -90.000000                  0.000000             0.000000          0.000000                  0.000000                0.000000            -84.000000
25%     28545.250000  1.440815e+09      1.000000     22.000000      3.000000    767.000000    746.000000      2.000000      0.000000      0.000000      7.000000     25.000000      3.000000    740.000000    708.000000      2.000000      0.000000      0.000000      7.000000     25.000000      3.000000    736.000000    705.000000      2.000000      0.000000      0.000000      7.000000     25.000000      3.000000    716.000000    692.000000      2.000000      0.000000      0.000000      7.000000     25.000000      3.000000    717.000000    690.000000      2.000000      0.000000      0.000000      7.000000     23.000000      3.000000    779.000000    757.000000      2.000000      0.000000      0.000000      7.000000     25.000000      3.000000    755.000000    718.000000      2.000000      0.000000      0.000000      7.000000     25.000000      3.000000    750.000000    712.000000      2.000000      0.000000      0.000000      7.000000     25.000000      3.000000    733.000000    701.000000      2.000000      0.000000      0.000000      7.000000     25.000000      3.000000    735.000000    701.000000      2.000000      0.000000      0.000000      7.000000          0.000000          0.000000             0.000000             0.000000            45.000000            -86.000000                     0.000000                2.000000             3.000000                     2.000000                   0.000000               -31.000000         42.000000         -86.000000                  0.000000             2.000000          3.000000                  2.000000                0.000000            -31.000000
50%     57160.500000  1.446338e+09      1.000000     50.000000      3.000000   1175.000000   1113.000000     11.000000      0.000000      0.000000      8.000000     50.000000      3.000000   1109.000000   1054.000000      9.000000      0.000000      0.000000      8.000000     51.000000      3.000000   1101.000000   1040.000000      9.000000      0.000000      0.000000      8.000000     51.000000      3.000000   1066.000000   1017.000000      8.000000      0.000000      0.000000      8.000000     51.000000      3.000000   1063.000000   1012.000000      8.000000      0.000000      0.000000      8.000000     50.000000      3.000000   1191.000000   1121.000000     11.000000      0.000000      0.000000      8.000000     51.000000      3.000000   1131.000000   1059.000000      9.000000      0.000000      0.000000      8.000000     51.000000      3.000000   1121.000000   1051.000000      9.000000      0.000000      0.000000      8.000000     51.000000      3.000000   1092.000000   1028.000000      8.000000      0.000000      0.000000      8.000000     51.000000      3.000000   1096.000000   1027.000000      8.000000      0.000000      0.000000      8.000000         61.000000          0.000000             3.000000             0.000000           118.000000            -83.000000                   189.000000                3.000000             3.000000                     2.000000                   1.000000               -14.000000        118.000000         -84.000000                189.000000             3.000000          3.000000                  2.000000                1.000000            -15.000000
75%     85755.750000  1.448829e+09      7.000000     75.000000      4.000000   1704.000000   1479.000000     19.000000      1.000000      1.000000     10.000000     75.000000      4.000000   1641.000000   1434.000000     18.000000      1.000000      1.000000     10.000000     76.000000      4.000000   1628.000000   1424.000000     18.000000      1.000000      1.000000     10.000000     78.000000      4.000000   1594.000000   1404.000000     17.000000      1.000000      1.000000     10.000000     76.000000      4.000000   1594.000000   1404.000000     17.000000      1.000000      1.000000     10.000000     75.000000      4.000000   1702.000000   1477.000000     19.000000      1.000000      1.000000     10.000000     76.000000      4.000000   1643.000000   1430.000000     18.000000      1.000000      1.000000     10.000000     75.000000      4.000000   1637.000000   1424.000000     18.000000      1.000000      1.000000     10.000000     76.000000      4.000000   1604.000000   1409.000000     17.000000      1.000000      1.000000     10.000000     78.000000      4.000000   1615.000000   1409.000000     17.000000      1.000000      1.000000     10.000000        139.000000          1.000000             6.000000             5.000000           158.000000            -79.000000                   223.000000                4.000000             4.000000                     3.000000                   1.000000                 9.000000        158.000000         -79.000000                222.000000             4.000000          4.000000                  3.000000                1.000000              8.000000
max    114406.000000  1.450313e+09      7.000000    112.000000      6.000000   3319.000000   4332.000000     47.000000      8.000000      5.000000     34.000000    112.000000      6.000000   3234.000000   4136.000000     44.000000      8.000000      6.000000     33.000000    112.000000      7.000000   3115.000000   3740.000000     51.000000      8.000000      6.000000     83.000000    112.000000      7.000000   3308.000000   3782.000000     50.000000      8.000000      8.000000     33.000000    112.000000      6.000000   3224.000000   3840.000000     45.000000      7.000000      6.000000     23.000000    112.000000      7.000000   3457.000000   4734.000000     45.000000      7.000000      6.000000     26.000000    112.000000      7.000000   3371.000000   3764.000000     45.000000      8.000000      6.000000     24.000000    112.000000      7.000000   3208.000000   3446.000000     46.000000      8.000000      5.000000     29.000000    112.000000      7.000000   3133.000000   3661.000000     46.000000      8.000000      5.000000     31.000000    112.000000      7.000000   3525.000000   4788.000000     50.000000      9.000000      7.000000     25.000000        300.000000          1.000000             9.000000             9.000000           300.000000            300.000000                   300.000000               81.000000             8.000000                    10.000000                  25.000000               300.000000        300.000000         296.000000                300.000000            21.000000          9.000000                  9.000000               13.000000            300.000000